<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash; 
use Illuminate\Support\Str; 

class RoyaltiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('royalties')->insert(

            [

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'STAY', 
                    'song_name' => 'STAY.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '2978', 
                    'downloads' => '', 
                    'revenue' => '10.719', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'FAMEYE',
                    'release_name' => 'DESTINY', 
                    'song_name' => 'Destiny.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '6538', 
                    'downloads' => '1', 
                    'revenue' => '25.901', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'Fameye - Oct.jpg',
                ],

                [ 
                    'username' => 'FAMEYE',
                    'release_name' => 'CHAIRMAN', 
                    'song_name' => 'Chairman.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '9790', 
                    'downloads' => '4', 
                    'revenue' => '42.365', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'Fameye - Oct.jpg',
                ],

                [ 
                    'username' => 'fredarhymz',
                    'release_name' => 'SING MY SONG', 
                    'song_name' => 'Sing my Song.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '975', 
                    'downloads' => '0', 
                    'revenue' => '2.926', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'Freda Rhymz - Oct.png',
                ],

                [ 
                    'username' => 'FAMEYE',
                    'release_name' => 'NOTIN I GET', 
                    'song_name' => 'Notin i get.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '12039', 
                    'downloads' => '7', 
                    'revenue' => '51.997', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'Fameye - Oct.jpg',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'MONKEY NO FINE', 
                    'song_name' => 'Monkey no fine.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '220', 
                    'downloads' => '0', 
                    'revenue' => '1.023', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'FORGET ME NOT', 
                    'song_name' => 'Forget me not.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '138', 
                    'downloads' => '', 
                    'revenue' => '0.729', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'HEAVEN OR HELL', 
                    'song_name' => 'Heaven or Hell.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '56', 
                    'downloads' => '', 
                    'revenue' => '0.119', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'LIGHTS IN THE SKY', 
                    'song_name' => 'Lights in the Sky.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '35', 
                    'downloads' => '', 
                    'revenue' => '0.156', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'DIE YOUNG', 
                    'song_name' => 'Die Young.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '32', 
                    'downloads' => '', 
                    'revenue' => '0.133', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'THA BOUNCE', 
                    'song_name' => 'Tha Bounce.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '31', 
                    'downloads' => '', 
                    'revenue' => '0.124', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'NIGHT AND DAY', 
                    'song_name' => 'Night and Day.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '132', 
                    'downloads' => '', 
                    'revenue' => '0.563', 
                    'period_gained'=> 'OCT-19', 
                    'image_file' => 'D-Black Oct.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'STAY', 
                    'song_name' => 'STAY.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '1258', 
                    'downloads' => '', 
                    'revenue' => '2.585', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'MONKEY NO FINE', 
                    'song_name' => 'Monkey no fine.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '90', 
                    'downloads' => '', 
                    'revenue' => '0.848', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'FORGET ME NOT', 
                    'song_name' => 'Forget me not.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '151', 
                    'downloads' => '', 
                    'revenue' => '1.061', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'HEAVEN OR HELL', 
                    'song_name' => 'Heaven or Hell.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '102', 
                    'downloads' => '', 
                    'revenue' => '0.811', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'LIGHTS IN THE SKY', 
                    'song_name' => 'Lights in the Sky.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '40', 
                    'downloads' => '', 
                    'revenue' => '0.553', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'DIE YOUNG', 
                    'song_name' => 'Die Young.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '35', 
                    'downloads' => '', 
                    'revenue' => '0.587', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'THA BOUNCE', 
                    'song_name' => 'Tha Bounce.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '38', 
                    'downloads' => '', 
                    'revenue' => '0.551', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'NIGHT AND DAY', 
                    'song_name' => 'Night and Day.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '193', 
                    'downloads' => '', 
                    'revenue' => '1.231', 
                    'period_gained'=> 'AUG-19', 
                    'image_file' => 'Screenshot (3).png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'FORGET ME NOT', 
                    'song_name' => 'Forget me not.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '350', 
                    'downloads' => '', 
                    'revenue' => '0.993', 
                    'period_gained'=> 'JUN-19', 
                    'image_file' => 'dblack jun.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'NIGHT AND DAY', 
                    'song_name' => 'Night and Day.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '1776', 
                    'downloads' => '', 
                    'revenue' => '5.838', 
                    'period_gained'=> 'JUN-19', 
                    'image_file' => 'dblack jun.png',
                ],

                
                [ 
                    'username' => 'DBlack',
                    'release_name' => 'HEAVEN OR HELL', 
                    'song_name' => 'Heaven or Hell.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => 'Heaven or Hell.mp3', 
                    'downloads' => '', 
                    'revenue' => '3.198', 
                    'period_gained'=> 'JUN-19', 
                    'image_file' => 'dblack jun.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'MONKEY NO FINE', 
                    'song_name' => 'Monkey no fine.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '420', 
                    'downloads' => '', 
                    'revenue' => '1.778', 
                    'period_gained'=> 'JUN-19', 
                    'image_file' => 'dblack jun.png',
                ],

                [ 
                    'username' => 'DBlack',
                    'release_name' => 'LIGHTS IN THE SKY', 
                    'song_name' => 'Lights in the Sky.mp3', 
                    'spotify_streams'=>'',
                    'applemusic_streams' =>'',
                    'deezer_streams' => '', 
                    'youtube_streams' => '', 
                    'tidal_streams' => '', 
                    'amazonmusic_streams' => '', 
                    'total_streams' => '328', 
                    'downloads' => '', 
                    'revenue' => '0.827', 
                    'period_gained'=> 'JUN-19', 
                    'image_file' => 'dblack jun.png',
                ],


            ]

            );
    }
}
