<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SongsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $songs = array(
            array('id' => '1','username' => 'java','release_name' => 'BINGY','songs' => 'DADDY LUMBA - ABEN WO HA.mp3','status' => 'Bad','trans_time' => '15:31:33pm','trans_date' => '2019-05-09'),
            array('id' => '2','username' => 'java','release_name' => 'BINGY','songs' => 'Daddy Lumba - Akoma Da Akoma So.mp3','status' => 'Bad','trans_time' => '15:31:33pm','trans_date' => '2019-05-09'),
            array('id' => '3','username' => 'FRIMPONG','release_name' => 'MY CRUSH','songs' => 'here i am to worship u.mp3','status' => 'Bad','trans_time' => '23:03:53pm','trans_date' => '2019-11-04'),
            array('id' => '4','username' => 'cgtnWlyaucPp3hXAjOXJ4A==','release_name' => 'xxmqHv5Z0a+fklg5zEDRuA==','songs' => 'Fa6aLuOcfe1lGdBkqjx6M0OlMB4koAYdSVHh6n3Glu1jYEaSCn7Zuwzy3SZhzm0L','status' => 'viAa1Xuk2nPHYQqTA5X6gw==','trans_time' => '15:17:48pm','trans_date' => '2019-11-10'),
            array('id' => '5','username' => 'Lil Lunna','release_name' => 'CHASE MONEY','songs' => '','status' => 'Good','trans_time' => '09:59:28am','trans_date' => '2019-11-15'),
            array('id' => '6','username' => 'sabbirdj','release_name' => 'MURKHO MEYE','songs' => 'Murkho-Meye-Mastring.mp3','status' => 'Good','trans_time' => '08:57:18am','trans_date' => '2019-11-21'),
            array('id' => '7','username' => 'KwameBaahGH','release_name' => 'GOD BLESS YOU','songs' => 'kwame Baah.mp3','status' => 'Good','trans_time' => '09:51:51am','trans_date' => '2019-11-21'),
            array('id' => '8','username' => 'terbang321','release_name' => 'SCRUFFY','songs' => 'TER_BANG_-_wassup[1].mp3','status' => 'Good','trans_time' => '15:04:40pm','trans_date' => '2019-11-22'),
            array('id' => '9','username' => 'fareal','release_name' => 'DON&#39;T KEEP ME WAITING','songs' => 'Dont Keep Me Waiting.mp3','status' => 'Bad','trans_time' => '11:31:01am','trans_date' => '2019-12-05'),
            array('id' => '10','username' => 'fareal','release_name' => 'LOOK','songs' => 'AUD-20191205-WA0218.mp3','status' => 'Good','trans_time' => '11:43:42am','trans_date' => '2019-12-05'),
            array('id' => '11','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '12','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '13','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '14','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '15','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '16','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '17','username' => 'DBlack','release_name' => 'SMOKE & MIRRORS','songs' => 'd black.mp3','status' => 'Bad','trans_time' => '17:41:29pm','trans_date' => '2019-12-09'),
            array('id' => '18','username' => 'Winfredsai','release_name' => 'WHO’S YOUR DADDY','songs' => 'KingSai - juju(Prod by Kelvin Mabz & Nytwulf).mp3','status' => 'Good','trans_time' => '11:44:30am','trans_date' => '2019-12-17'),
            array('id' => '19','username' => 'FAMEYE','release_name' => 'NOTHING  I GET','songs' => 'fameye.mp3','status' => 'Bad','trans_time' => '09:49:19am','trans_date' => '2019-12-19'),
            array('id' => '20','username' => 'FRIMPONG','release_name' => 'GUR','songs' => 'fameye.mp3','status' => 'Bad','trans_time' => '02:32:41am','trans_date' => '2019-12-25'),
            array('id' => '21','username' => 'FRIMPONG','release_name' => 'BAE','songs' => 'fameye.mp3','status' => 'Bad','trans_time' => '06:38:51am','trans_date' => '2019-12-26'),
            array('id' => '22','username' => 'FAMEYE','release_name' => 'NOTIN I GET','songs' => 'Notin i get.mp3','status' => 'Good','trans_time' => '08:20:07am','trans_date' => '2020-01-04'),
            array('id' => '23','username' => 'FAMEYE','release_name' => 'CHAIRMANN','songs' => 'Chairman.mp3','status' => 'Bad','trans_time' => '08:27:33am','trans_date' => '2020-01-04'),
            array('id' => '24','username' => 'FAMEYE','release_name' => 'DESTINY','songs' => 'Destiny.mp3','status' => 'Good','trans_time' => '08:29:47am','trans_date' => '2020-01-04'),
            array('id' => '25','username' => 'FAMEYE','release_name' => 'CHAIRMAN','songs' => 'chairman.mp3','status' => 'Bad','trans_time' => '22:18:04pm','trans_date' => '2020-01-05'),
            array('id' => '26','username' => 'fredarhymz','release_name' => 'SING MY SONG','songs' => 'Sing my Song.mp3','status' => 'Good','trans_time' => '22:32:23pm','trans_date' => '2020-01-05'),
            array('id' => '27','username' => 'DBlack','release_name' => 'STAY','songs' => 'STAY.mp3','status' => 'Good','trans_time' => '23:33:00pm','trans_date' => '2020-01-05'),
            array('id' => '28','username' => 'DBlack','release_name' => 'SMOKE AND MIRRORS','songs' => 'Monkey no fine.mp3','status' => 'Bad','trans_time' => '23:39:13pm','trans_date' => '2020-01-05'),
            array('id' => '29','username' => 'DBlack','release_name' => 'MONKEY NO FINE','songs' => 'Monkey no fine.mp3','status' => 'Good','trans_time' => '08:25:49am','trans_date' => '2020-01-06'),
            array('id' => '30','username' => 'DBlack','release_name' => 'NIGHT AND DAY','songs' => 'Night and Day.mp3','status' => 'Bad','trans_time' => '08:39:12am','trans_date' => '2020-01-06'),
            array('id' => '31','username' => 'DBlack','release_name' => 'FORGET ME NOT','songs' => 'Forget me not.mp3','status' => 'Good','trans_time' => '08:45:49am','trans_date' => '2020-01-06'),
            array('id' => '32','username' => 'DBlack','release_name' => 'HEAVEN OR HELL','songs' => 'Heaven or Hell.mp3','status' => 'Bad','trans_time' => '08:53:57am','trans_date' => '2020-01-06'),
            array('id' => '33','username' => 'DBlack','release_name' => 'LIGHTS IN THE SKY','songs' => 'Lights in the Sky.mp3','status' => 'Good','trans_time' => '08:57:58am','trans_date' => '2020-01-06'),
            array('id' => '34','username' => 'DBlack','release_name' => 'DIE YOUNG','songs' => 'Die Young.mp3','status' => 'Bad','trans_time' => '08:59:50am','trans_date' => '2020-01-06'),
            array('id' => '35','username' => 'DBlack','release_name' => 'THA BOUNCE','songs' => 'Tha Bounce.mp3','status' => 'Good','trans_time' => '09:01:56am','trans_date' => '2020-01-06'),
            array('id' => '36','username' => 'FAMEYE','release_name' => 'CHAIRMAN','songs' => 'Chairman.mp3','status' => 'Good','trans_time' => '16:09:35pm','trans_date' => '2020-01-06'),
            array('id' => '37','username' => 'DBlack','release_name' => 'NIGHT AND DAY','songs' => 'Night and Day.mp3','status' => 'Good','trans_time' => '09:52:26am','trans_date' => '2020-01-08'),
            array('id' => '38','username' => 'Officialbanga1','release_name' => 'OPTION$','songs' => 'PicsArt_11-29-01.04.41 (1).jpg','status' => 'Bad','trans_time' => '12:17:49pm','trans_date' => '2020-01-14'),
            array('id' => '39','username' => 'Itz Tee N','release_name' => 'SHISHEHO','songs' => 'Itz Tee N_Shisheho_ft Ohemaa Lizzy(Prod. By Mr Cue).mp3','status' => 'Bad','trans_time' => '17:16:58pm','trans_date' => '2020-01-29'),
            array('id' => '40','username' => 'Itz Tee N','release_name' => 'NYAME NA WAYE','songs' => 'Itz Tee N_Nyame Na waye ft OJay(Prod by Mr Cue).mp3','status' => 'Good','trans_time' => '17:41:04pm','trans_date' => '2020-01-29'),
            array('id' => '41','username' => 'Chikel Baibe','release_name' => 'KWEKU','songs' => 'Kweku (Prod By AbeBeatz) (Ghxclusives.com)','status' => 'Bad','trans_time' => '07:28:13am','trans_date' => '2020-02-02'),
            array('id' => '42','username' => 'UBUNTUBROTHERS','release_name' => 'SLAY QUEEN','songs' => 'Ubuntu Brothers & Native Soul - Slay Queen ft. Siko.mp3','status' => 'Bad','trans_time' => '09:17:36am','trans_date' => '2020-02-05'),
            array('id' => '43','username' => 'FAMEYE','release_name' => 'TGIF','songs' => 'TGIF.mp3','status' => 'Bad','trans_time' => '17:24:43pm','trans_date' => '2020-02-05'),
            array('id' => '44','username' => 'FAMEYE','release_name' => 'ADDICTION','songs' => 'ADDICTION.mp3','status' => 'Bad','trans_time' => '17:27:14pm','trans_date' => '2020-02-05'),
            array('id' => '45','username' => 'FAMEYE','release_name' => 'SIKA DURO','songs' => 'Sika Duro.mp3','status' => 'Bad','trans_time' => '17:31:25pm','trans_date' => '2020-02-05'),
            array('id' => '46','username' => 'FAMEYE','release_name' => 'BARMAN','songs' => 'Barman.mp3','status' => 'Bad','trans_time' => '17:34:37pm','trans_date' => '2020-02-05'),
            array('id' => '47','username' => 'FAMEYE','release_name' => 'MA MIND DEY','songs' => 'Ma Mind Dey.mp3','status' => 'Bad','trans_time' => '17:36:43pm','trans_date' => '2020-02-05'),
            array('id' => '48','username' => 'FAMEYE','release_name' => 'AFIA BRUWAA','songs' => 'Afia Bruwaa.mp3','status' => 'Bad','trans_time' => '17:39:24pm','trans_date' => '2020-02-05'),
            array('id' => '49','username' => 'FAMEYE','release_name' => '3B3FA','songs' => '3b3fa.mp3','status' => 'Bad','trans_time' => '17:50:32pm','trans_date' => '2020-02-05'),
            array('id' => '50','username' => 'FAMEYE','release_name' => 'ENKWA','songs' => 'Enkwa.mp3','status' => 'Bad','trans_time' => '18:32:06pm','trans_date' => '2020-02-05'),
            array('id' => '51','username' => 'FAMEYE','release_name' => 'NYAME B3Y3','songs' => 'Nyame B3y3.mp3','status' => 'Bad','trans_time' => '18:34:39pm','trans_date' => '2020-02-05'),
            array('id' => '52','username' => 'FAMEYE','release_name' => 'THRILLER','songs' => 'Thriller.mp3','status' => 'Bad','trans_time' => '18:36:42pm','trans_date' => '2020-02-05'),
            array('id' => '53','username' => 'FAMEYE','release_name' => 'MATI','songs' => 'Mati.mp3','status' => 'Bad','trans_time' => '23:00:57pm','trans_date' => '2020-02-05'),
            array('id' => '54','username' => 'Yawbeats','release_name' => 'FREE] BURNABOY X REMA X KWESI ARTHUR TYPE BEAT','songs' => 'BURNABOY MR EAZI KWESI ARTHUR TYP3.mp3','status' => 'Bad','trans_time' => '02:53:28am','trans_date' => '2020-02-08'),
            array('id' => '55','username' => 'Kenx music','release_name' => 'ON MY MIND','songs' => 'Sugar mummy.mp3','status' => 'Good','trans_time' => '18:12:08pm','trans_date' => '2020-02-12'),
            array('id' => '56','username' => 'KOSTASPEED','release_name' => 'MAKE YOU MOVE (ORIGINAL MIX)','songs' => 'KostaSpeed-Make you move (Original  Mix).mp3','status' => 'Bad','trans_time' => '08:59:24am','trans_date' => '2020-02-22'),
            array('id' => '57','username' => 'Yawbeats','release_name' => 'GANG','songs' => 'Yawbeats _Gang_Afro insrtumentals Produced by Yawbeats.mp3','status' => 'Bad','trans_time' => '02:38:55am','trans_date' => '2020-02-25'),
            array('id' => '58','username' => 'Jay Jnr','release_name' => 'GHETTO KIDS','songs' => 'AUDIO-2019-09-22-19-46-29.mp3','status' => 'Bad','trans_time' => '15:48:05pm','trans_date' => '2020-03-05'),
            array('id' => '59','username' => 'Jay Jnr','release_name' => 'GHETTO KIDS','songs' => 'AUDIO-2019-08-09-20-15-28.mp3','status' => 'Bad','trans_time' => '15:48:05pm','trans_date' => '2020-03-05'),
            array('id' => '60','username' => 'Jay Jnr','release_name' => 'WE AT THE ALBUM','songs' => 'AUDIO-2019-08-09-20-15-28.mp3','status' => 'Bad','trans_time' => '20:47:45pm','trans_date' => '2020-03-06'),
            array('id' => '61','username' => 'FAMEYE','release_name' => 'SPEED UP','songs' => 'Fameye - Speed Up.mp3','status' => 'Bad','trans_time' => '20:38:43pm','trans_date' => '2020-03-07'),
            array('id' => '62','username' => 'KYLEM','release_name' => 'KAKYERE ME','songs' => 'KyleM - Kakyere Me [ Prod. By TubhaniMuzik ].mp3','status' => 'Bad','trans_time' => '21:22:16pm','trans_date' => '2020-03-12'),
            array('id' => '63','username' => 'Phrimpong','release_name' => 'LIVE NOW LOVE NOW','songs' => 'Live Now Love Now.mp3','status' => 'Bad','trans_time' => '17:56:10pm','trans_date' => '2020-03-13'),
            array('id' => '64','username' => 'Phrimpong','release_name' => 'CHECK','songs' => 'Check.mp3','status' => 'Bad','trans_time' => '17:57:46pm','trans_date' => '2020-03-13'),
            array('id' => '65','username' => 'Phrimpong','release_name' => 'SIKA NE DINPA','songs' => 'Sika ne Dinpa.mp3','status' => 'Bad','trans_time' => '17:59:11pm','trans_date' => '2020-03-13'),
            array('id' => '66','username' => 'Phrimpong','release_name' => 'ODEHYIE','songs' => 'Odehyie.mp3','status' => 'Bad','trans_time' => '18:00:43pm','trans_date' => '2020-03-13'),
            array('id' => '67','username' => 'Phrimpong','release_name' => 'DEAR CRUSH','songs' => 'Dear Crush.mp3','status' => 'Good','trans_time' => '18:02:18pm','trans_date' => '2020-03-13'),
            array('id' => '68','username' => 'Phrimpong','release_name' => 'NOTE TO FAMILY','songs' => 'Note to Family.mp3','status' => 'Good','trans_time' => '18:08:25pm','trans_date' => '2020-03-13'),
            array('id' => '69','username' => 'Phrimpong','release_name' => 'INTERLUDE','songs' => 'Interlude.mp3','status' => 'Bad','trans_time' => '18:09:52pm','trans_date' => '2020-03-13'),
            array('id' => '70','username' => 'GeorgePraize','release_name' => 'MIRACLE GOD','songs' => '','status' => 'Bad','trans_time' => '05:37:30am','trans_date' => '2020-03-21'),
            array('id' => '71','username' => 'fredarhymz','release_name' => 'AGORO','songs' => 'Agoro .mp3','status' => 'Bad','trans_time' => '07:16:50am','trans_date' => '2020-04-05'),
            array('id' => '72','username' => 'arief iskandar music','release_name' => 'HADIRMU BAGAI MIMPI','songs' => 'Hadirmu Bagai Mimpi.mp3','status' => 'Good','trans_time' => '01:34:06am','trans_date' => '2020-04-20'),
            array('id' => '73','username' => 'arief iskandar music','release_name' => 'MEMANDANGMU','songs' => 'Memandangmu.mp3','status' => 'Bad','trans_time' => '02:00:02am','trans_date' => '2020-04-20'),
            array('id' => '74','username' => 'arief iskandar music','release_name' => 'SECAWAN MADU','songs' => 'Secawan Madu.mp3','status' => 'Bad','trans_time' => '04:39:46am','trans_date' => '2020-04-20'),
            array('id' => '75','username' => 'arief iskandar music','release_name' => 'KESEPIAN','songs' => 'Kesepian.mp3','status' => 'Good','trans_time' => '08:13:13am','trans_date' => '2020-04-20'),
            array('id' => '76','username' => 'Myra Kay','release_name' => 'PIESIE','songs' => 'Piesie.mp3','status' => 'Good','trans_time' => '17:56:46pm','trans_date' => '2020-05-04'),
            array('id' => '77','username' => 'Myra Kay','release_name' => 'PROVE IT','songs' => 'Prove it.mp3','status' => 'Bad','trans_time' => '18:00:10pm','trans_date' => '2020-05-04'),
            array('id' => '78','username' => 'jamarjargo','release_name' => 'MISSING','songs' => 'J Bixil Ft.Maxi Made - Missing.mp3','status' => 'Good','trans_time' => '04:18:43am','trans_date' => '2020-05-14'),
            array('id' => '79','username' => 'jamarjargo','release_name' => 'DEEN OVER DUNIYA','songs' => 'Jamar Jargo - Deen Over Duniya Ft.Castillo Nasheeds.mp3','status' => 'Good','trans_time' => '05:53:20am','trans_date' => '2020-05-14'),
            array('id' => '80','username' => 'DJ LuHleRh','release_name' => 'EMPTY ROOM','songs' => 'LuHleRh_-_Empty Room _1588332716.mp3','status' => 'Bad','trans_time' => '19:00:33pm','trans_date' => '2020-05-16'),
            array('id' => '81','username' => 'DJ LuHleRh','release_name' => 'MORE FORCE (ORIGINAL MIX)','songs' => 'LuHleRh_-_Focus (Original Mix) (1).mp3','status' => 'Bad','trans_time' => '19:08:08pm','trans_date' => '2020-05-16'),
            array('id' => '82','username' => 'UBUNTU BROTHERS','release_name' => 'ROAD TO GANGSTER MUSIQ 2','songs' => 'Pablo Le Bee -Alone_(Christian BassMachine).mp3','status' => 'Bad','trans_time' => '17:47:11pm','trans_date' => '2020-05-25'),
            array('id' => '83','username' => 'UBUNTU BROTHERS','release_name' => 'ROAD TO GANGSTER MUSIQ 2','songs' => '','status' => 'Good','trans_time' => '17:47:11pm','trans_date' => '2020-05-25'),
            array('id' => '84','username' => 'UBUNTU BROTHERS','release_name' => 'ROAD TO GANGSTER MUSIQ 2','songs' => 'Pablo Le Bee -Nko NKo Nko_Thebelebe_(Christian BassMachine).mp3','status' => 'Good','trans_time' => '17:47:11pm','trans_date' => '2020-05-25'),
            array('id' => '85','username' => 'UBUNTU BROTHERS','release_name' => 'ROAD TO GANGSTER MUSIQ 2','songs' => 'Pablo Le Bee -Zenze_Xo69(Christian BassMachine.mp3','status' => 'Good','trans_time' => '17:47:11pm','trans_date' => '2020-05-25'),
            array('id' => '86','username' => 'UBUNTU BROTHERS','release_name' => 'ROAD TO GANGSTER MUSIQ 2','songs' => '','status' => 'Bad','trans_time' => '17:47:11pm','trans_date' => '2020-05-25'),
            array('id' => '87','username' => 'DBlack','release_name' => 'HEAVEN OR HELL','songs' => 'Heaven or Hell.mp3','status' => 'Good','trans_time' => '08:48:55am','trans_date' => '2020-06-03'),
            array('id' => '88','username' => 'DBlack','release_name' => 'DIE YOUNG','songs' => 'Die Young.mp3','status' => 'Bad','trans_time' => '08:51:55am','trans_date' => '2020-06-03'),
            array('id' => '89','username' => 'FAMEYE','release_name' => 'GBWUL2018308','songs' => 'Obolo.mp3','status' => 'Bad','trans_time' => '09:24:21am','trans_date' => '2020-06-03'),
            array('id' => '90','username' => 'FAMEYE','release_name' => 'GBWUL2039612','songs' => 'Long life.mp3','status' => 'Good','trans_time' => '09:27:47am','trans_date' => '2020-06-03'),
            array('id' => '91','username' => 'FAMEYE','release_name' => 'MATI','songs' => 'Mati.mp3','status' => 'Good','trans_time' => '17:26:40pm','trans_date' => '2020-06-03'),
            array('id' => '92','username' => 'FAMEYE','release_name' => 'SIKA DURO','songs' => 'Sika duro.mp3','status' => 'Bad','trans_time' => '22:31:40pm','trans_date' => '2020-06-03'),
            array('id' => '93','username' => 'FAMEYE','release_name' => 'BARMAN','songs' => 'Barman.mp3','status' => 'Bad','trans_time' => '22:35:06pm','trans_date' => '2020-06-03'),
            array('id' => '94','username' => 'FAMEYE','release_name' => 'MA MIND DEY','songs' => 'Ma mind Dey.mp3','status' => 'Bad','trans_time' => '22:40:11pm','trans_date' => '2020-06-03'),
            array('id' => '95','username' => 'FAMEYE','release_name' => 'NYAME B3Y3','songs' => 'Nyame B3y3.mp3','status' => 'Good','trans_time' => '22:54:03pm','trans_date' => '2020-06-03'),
            array('id' => '96','username' => 'FAMEYE','release_name' => 'ENKWA','songs' => 'Enkwa.mp3','status' => 'Bad','trans_time' => '06:47:54am','trans_date' => '2020-06-04'),
            array('id' => '97','username' => 'FAMEYE','release_name' => 'ADDICTION','songs' => 'Addiction.mp3','status' => 'Good','trans_time' => '07:01:39am','trans_date' => '2020-06-04'),
            array('id' => '98','username' => 'FAMEYE','release_name' => 'TGIF','songs' => 'TGIF.mp3','status' => 'Good','trans_time' => '07:03:48am','trans_date' => '2020-06-04'),
            array('id' => '99','username' => 'FAMEYE','release_name' => 'AFIA BRUWAA','songs' => 'Afia Bruwaa.mp3','status' => 'Good','trans_time' => '07:06:30am','trans_date' => '2020-06-04'),
            array('id' => '100','username' => 'FAMEYE','release_name' => 'BISA','songs' => 'Bisa.mp3','status' => 'Bad','trans_time' => '07:10:37am','trans_date' => '2020-06-04'),
            array('id' => '101','username' => 'FAMEYE','release_name' => '3B3FA','songs' => '3b3fa.mp3','status' => 'Bad','trans_time' => '07:13:21am','trans_date' => '2020-06-04'),
            array('id' => '102','username' => 'FAMEYE','release_name' => 'THRILLER','songs' => 'Thriller.mp3','status' => 'Good','trans_time' => '07:15:40am','trans_date' => '2020-06-04'),
            array('id' => '103','username' => 'fredarhymz','release_name' => 'GBWUL2080965','songs' => 'KMT.mp3','status' => 'Good','trans_time' => '09:31:36am','trans_date' => '2020-07-03'),
            array('id' => '104','username' => 'abuhuda5','release_name' => 'BLACK LIVES MATTER (THEME SONG)','songs' => 'Nicky Miraj ft Sqube.mp3','status' => 'Bad','trans_time' => '21:20:18pm','trans_date' => '2020-07-16'),
            array('id' => '105','username' => 'fredarhymz','release_name' => 'GBWUL2091004','songs' => 'Point of Correction.mp3','status' => 'Good','trans_time' => '09:04:12am','trans_date' => '2020-08-04'),
            array('id' => '106','username' => 'fredarhymz','release_name' => 'GBWUL1958151','songs' => 'Agoro.mp3','status' => 'Bad','trans_time' => '09:28:10am','trans_date' => '2020-08-04'),
            array('id' => '107','username' => 'Phrimpong','release_name' => 'CHECK','songs' => 'Check.mp3','status' => 'Good','trans_time' => '08:49:52am','trans_date' => '2020-08-06'),
            array('id' => '108','username' => 'Phrimpong','release_name' => 'SIKA NE DINPA','songs' => 'Sika ne Dinpa.mp3','status' => 'Bad','trans_time' => '08:51:42am','trans_date' => '2020-08-06'),
            array('id' => '109','username' => 'Phrimpong','release_name' => 'INTERLUDE','songs' => 'Interlude.mp3','status' => 'Bad','trans_time' => '08:53:11am','trans_date' => '2020-08-06'),
            array('id' => '110','username' => 'Myra Kay','release_name' => 'PROVE IT','songs' => 'Prove It.mp3','status' => 'Bad','trans_time' => '08:56:10am','trans_date' => '2020-08-06'),
            array('id' => '111','username' => 'fredarhymz','release_name' => 'QZHZ42063796','songs' => 'Public Opinion.mp3','status' => 'Bad','trans_time' => '09:45:47am','trans_date' => '2020-09-03'),
            array('id' => '112','username' => 'OokomfoooKwadee33','release_name' => '755773131634','songs' => 'The Compilation.mp3','status' => 'Bad','trans_time' => '14:00:50pm','trans_date' => '2020-09-03'),
            array('id' => '113','username' => 'OokomfoooKwadee33','release_name' => '755773128306','songs' => 'Abro Ne Bayie.mp3','status' => 'Good','trans_time' => '14:14:19pm','trans_date' => '2020-09-03'),
            array('id' => '114','username' => 'OokomfoooKwadee33','release_name' => '755773127538','songs' => 'Me Toaso.mp3','status' => 'Good','trans_time' => '17:10:28pm','trans_date' => '2020-09-03'),
            array('id' => '115','username' => 'OokomfoooKwadee33','release_name' => '755773130774','songs' => 'Nsem Pii.mp3','status' => 'Good','trans_time' => '17:14:08pm','trans_date' => '2020-09-03'),
            array('id' => '116','username' => 'OokomfoooKwadee33','release_name' => '755773129419','songs' => 'Okomfour Se Koo.mp3','status' => 'Good','trans_time' => '17:17:22pm','trans_date' => '2020-09-03'),
            array('id' => '117','username' => 'Fantana','release_name' => 'GBWUL2045366','songs' => 'Backstabbers.mp3','status' => 'Bad','trans_time' => '13:28:53pm','trans_date' => '2020-09-05'),
            array('id' => '118','username' => 'Fantana','release_name' => 'GBWUL2016817','songs' => 'Rich Gyal Anthem.mp3','status' => 'Good','trans_time' => '13:31:05pm','trans_date' => '2020-09-05'),
            array('id' => '119','username' => 'FAMEYE','release_name' => 'OKOMFOUR KWADEE','songs' => 'Okomfour Kwadee.mp3','status' => 'Bad','trans_time' => '13:36:43pm','trans_date' => '2020-09-05'),
            array('id' => '120','username' => 'Phrimpong','release_name' => 'EFIE NIPA','songs' => 'Efie Nipa.mp3','status' => 'Bad','trans_time' => '13:39:04pm','trans_date' => '2020-09-05'),
            array('id' => '121','username' => 'Arold','release_name' => 'MADE IN GHANA','songs' => 'Made In Ghana Album.mp3','status' => 'Good','trans_time' => '09:08:08am','trans_date' => '2020-09-11'),
            array('id' => '122','username' => 'Arold','release_name' => 'KPA','songs' => 'Kpa.mp3','status' => 'Good','trans_time' => '09:10:51am','trans_date' => '2020-09-11'),
            array('id' => '123','username' => 'Arold','release_name' => 'FAITHFUL','songs' => 'Faithful.mp3','status' => 'Bad','trans_time' => '09:14:13am','trans_date' => '2020-09-11'),
            array('id' => '124','username' => 'Arold','release_name' => 'ENO BE MY MATTER','songs' => 'Eno Be My Matter.mp3','status' => 'Bad','trans_time' => '09:17:04am','trans_date' => '2020-09-11'),
            array('id' => '125','username' => 'FRIMPONG','release_name' => 'GHOST','songs' => 'Bra.mp3','status' => 'Bad','trans_time' => '09:20:05am','trans_date' => '2020-09-11'),
            array('id' => '126','username' => 'FRIMPONG','release_name' => 'GHOST','songs' => 'Faithful.mp3','status' => 'Bad','trans_time' => '09:20:05am','trans_date' => '2020-09-11'),
            array('id' => '127','username' => 'FRIMPONG','release_name' => 'GHOST','songs' => 'Eno Be My Matter.mp3','status' => 'Bad','trans_time' => '09:20:05am','trans_date' => '2020-09-11'),
            array('id' => '128','username' => 'FRIMPONG','release_name' => 'GHOST','songs' => 'Small Small.mp3','status' => 'Bad','trans_time' => '09:20:05am','trans_date' => '2020-09-11'),
            array('id' => '129','username' => 'Arold','release_name' => 'MATE AHWE NE DO MU','songs' => 'Mate Ahwe Ne Do Mu.mp3','status' => 'Good','trans_time' => '09:31:02am','trans_date' => '2020-09-11'),
            array('id' => '130','username' => 'Arold','release_name' => 'BRA','songs' => 'Bra.mp3','status' => 'Bad','trans_time' => '15:00:43pm','trans_date' => '2020-09-11'),
            array('id' => '131','username' => 'Arold','release_name' => 'THE VERSATILE SHOW','songs' => 'The Versatile Show.mp3','status' => 'Bad','trans_time' => '15:03:11pm','trans_date' => '2020-09-11'),
            array('id' => '132','username' => 'Arold','release_name' => 'SMALL SMALL','songs' => 'Small Small.mp3','status' => 'Good','trans_time' => '15:05:30pm','trans_date' => '2020-09-11'),
            array('id' => '133','username' => 'Arold','release_name' => 'TENSION','songs' => 'Tension.mp3','status' => 'Good','trans_time' => '15:07:56pm','trans_date' => '2020-09-11'),
            array('id' => '134','username' => 'Arold','release_name' => 'MOBILE MONEY','songs' => 'Mobile money.mp3','status' => 'Bad','trans_time' => '15:16:11pm','trans_date' => '2020-09-11'),
            array('id' => '135','username' => 'Arold','release_name' => 'WOARA','songs' => 'Woara.mp3','status' => 'Good','trans_time' => '15:19:17pm','trans_date' => '2020-09-11'),
            array('id' => '136','username' => 'Arold','release_name' => 'ADONKO','songs' => 'Saucing.mp3','status' => 'Bad','trans_time' => '15:22:28pm','trans_date' => '2020-09-11'),
            array('id' => '137','username' => 'Arold','release_name' => 'SIKA','songs' => 'Sika.mp3','status' => 'Good','trans_time' => '15:25:34pm','trans_date' => '2020-09-11'),
            array('id' => '138','username' => 'Arold','release_name' => 'YOUTUBE','songs' => 'YOUTUBE.mp3','status' => 'Bad','trans_time' => '16:51:06pm','trans_date' => '2020-09-11'),
            array('id' => '139','username' => 'HD Empire Zambia','release_name' => 'WAKU KANYAFYE','songs' => 'HD Empire ft Chef 187__Wakukanyafye_Prod_By_Cassy Beats.mp3','status' => 'Good','trans_time' => '07:19:15am','trans_date' => '2020-10-13'),
            array('id' => '140','username' => 'HD Empire Zambia','release_name' => 'WAKU KANYAFYE 1','songs' => 'HD Empire ft Chef 187__Wakukanyafye_Prod_By_Cassy Beats.mp3','status' => 'Good','trans_time' => '07:22:20am','trans_date' => '2020-10-13'),
            array('id' => '141','username' => 'mrpercy','release_name' => 'QZHZ62017931','songs' => 'Focus.mp3','status' => 'Good','trans_time' => '09:55:08am','trans_date' => '2020-10-14'),
            array('id' => '142','username' => 'mrpercy','release_name' => 'YOUTUBE','songs' => 'YouTube .mp3','status' => 'Good','trans_time' => '10:02:54am','trans_date' => '2020-10-14'),
            array('id' => '143','username' => 'FAMEYE','release_name' => 'YOUTUBE','songs' => 'YouTube .mp3','status' => 'Good','trans_time' => '10:05:24am','trans_date' => '2020-10-14'),
            array('id' => '144','username' => 'fredarhymz','release_name' => 'QZHZ62008984','songs' => 'Saucy ft Sista Afia.mp3','status' => 'Good','trans_time' => '10:32:52am','trans_date' => '2020-10-16'),
            array('id' => '145','username' => 'YAW BERK','release_name' => 'QZHZ52075331','songs' => 'Independent Lady.mp3','status' => 'Good','trans_time' => '10:41:15am','trans_date' => '2020-10-16'),
            array('id' => '146','username' => 'Arold','release_name' => 'QZHZ52034409','songs' => 'Come Home.mp3','status' => 'Good','trans_time' => '10:44:22am','trans_date' => '2020-10-16'),
            array('id' => '147','username' => 'Phrimpong','release_name' => 'FIORKOR (FEAT. LINO BEEZY, MAX WALE, ANDY SCOTT)','songs' => '','status' => 'Good','trans_time' => '17:18:21pm','trans_date' => '2020-10-29'),
            array('id' => '148','username' => 'sidecut','release_name' => 'SURREY SHEHAR','songs' => 'Surrey Shehar without label.wav','status' => 'Bad','trans_time' => '00:06:24am','trans_date' => '2020-11-09'),
            array('id' => '149','username' => 'The official flyboy','release_name' => 'YA TRA','songs' => 'The Flyboy- Ya Tra(Mixed b_The Flyboy)','status' => 'Good','trans_time' => '08:02:35am','trans_date' => '2020-11-09'),
            array('id' => '150','username' => 'VC BLAQ','release_name' => 'FLOW','songs' => 'AUD-20201028-WA0006.mp3','status' => 'Good','trans_time' => '08:08:19am','trans_date' => '2020-11-09'),
            array('id' => '151','username' => 'Melchidaine','release_name' => 'SWEETIE','songs' => '','status' => 'Good','trans_time' => '08:54:27am','trans_date' => '2020-11-09'),
            array('id' => '152','username' => 'Phrimpong','release_name' => 'SHATTA WALE','songs' => 'Phrimpong_ Shatta Wale_ Prod. by Khendi.mp3','status' => 'Good','trans_time' => '21:31:54pm','trans_date' => '2020-11-10'),
            array('id' => '153','username' => 'Dopebwoy Kingpin','release_name' => 'YEYEI','songs' => 'dopebwoy-kingpin_y3y3.mp3','status' => 'Good','trans_time' => '08:18:44am','trans_date' => '2020-11-11'),
            array('id' => '154','username' => 'Dopebwoy Kingpin','release_name' => 'Y3','songs' => 'dopebwoy-kingpin_y3y3.mp3','status' => 'Good','trans_time' => '11:10:40am','trans_date' => '2020-11-11'),
            array('id' => '155','username' => 'Kwesi Law','release_name' => 'LOVE U LONG','songs' => 'Love U Long (Mixed by BeatzRanky)','status' => 'Good','trans_time' => '10:16:41am','trans_date' => '2020-11-12'),
            array('id' => '156','username' => 'blackness','release_name' => 'YEBEPIM','songs' => 'Blackboi Coba (1).mp3','status' => 'Bad','trans_time' => '19:12:47pm','trans_date' => '2020-11-13'),
            array('id' => '157','username' => 'blackness','release_name' => 'CHASING MONNEY','songs' => 'Black Boi Coba - Chasing Money(Mixed by Azee Burner) (1).mp3','status' => 'Good','trans_time' => '19:18:41pm','trans_date' => '2020-11-13'),
            array('id' => '158','username' => 'blackness','release_name' => 'YEBEPIM M','songs' => '','status' => 'Good','trans_time' => '19:23:00pm','trans_date' => '2020-11-13'),
            array('id' => '159','username' => 'minimoneygang','release_name' => 'NEW RAP FACE OF TM','songs' => 'minimoney gang mp3','status' => 'Bad','trans_time' => '13:10:25pm','trans_date' => '2020-11-17'),
            array('id' => '160','username' => 'opankagh','release_name' => 'QZNJW2096396','songs' => 'Eka Aba Fie.mp3','status' => 'Bad','trans_time' => '09:51:34am','trans_date' => '2020-11-19'),
            array('id' => '161','username' => 'Kweku Flick','release_name' => 'QZNJW2050895','songs' => 'Money (Acoustic).mp3','status' => 'Bad','trans_time' => '09:56:58am','trans_date' => '2020-11-19'),
            array('id' => '162','username' => 'Kweku Flick','release_name' => 'QZNJW2048927','songs' => 'Bye Bye.mp3','status' => 'Good','trans_time' => '10:07:32am','trans_date' => '2020-11-19'),
            array('id' => '163','username' => 'Amerado','release_name' => 'QZNJW2027349','songs' => 'Amerado - Kyere me ft Okyeame Kwame(Prod.by Azee Burner).mp3','status' => 'Good','trans_time' => '10:39:41am','trans_date' => '2020-11-19'),
            array('id' => '164','username' => 'K Quart','release_name' => 'YOU P3','songs' => 'K Quart- You p3 [Prod. by Survivor beatz].mp3','status' => 'Good','trans_time' => '22:13:06pm','trans_date' => '2020-11-21'),
            array('id' => '165','username' => 'minimoneygang','release_name' => 'NEW RAP FACE ÕF TM','songs' => 'minimoney gang mp3.mp3','status' => 'Good','trans_time' => '14:50:14pm','trans_date' => '2020-11-22'),
            array('id' => '166','username' => 'Kweku Flick','release_name' => 'QZNJW2050895','songs' => 'Money.mp3','status' => 'Good','trans_time' => '07:51:02am','trans_date' => '2020-12-01'),
            array('id' => '167','username' => 'Original capelo','release_name' => 'ONE DAY','songs' => 'AUD-20191228-WA0027.mp3','status' => 'Bad','trans_time' => '22:45:07pm','trans_date' => '2020-12-02'),
            array('id' => '168','username' => 'New_lordz','release_name' => 'MEYE YIE','songs' => 'Me Ye Yie - (Mixed By Dee Best) +23356530654','status' => 'Good','trans_time' => '23:14:20pm','trans_date' => '2020-12-05'),
            array('id' => '169','username' => 'YAW BERK','release_name' => 'QZMZ92039831','songs' => 'Inna Peace.mp3','status' => 'Good','trans_time' => '14:49:16pm','trans_date' => '2020-12-07'),
            array('id' => '170','username' => 'YAW BERK','release_name' => 'QZNJV2069343','songs' => 'Wonkwe.mp3','status' => 'Good','trans_time' => '14:56:52pm','trans_date' => '2020-12-07'),
            array('id' => '171','username' => 'BlackEagleEntertainment','release_name' => 'QZNJV2037482','songs' => 'Snapchat ft Medikal.mp3','status' => 'Good','trans_time' => '15:05:52pm','trans_date' => '2020-12-07'),
            array('id' => '172','username' => 'Shortcode','release_name' => 'SIKASWM','songs' => 'Shortcode ft Amakye The Rapper-Sikasem(Prod by BrakayDiDiT).mp3','status' => 'Good','trans_time' => '01:31:28am','trans_date' => '2020-12-11'),
            array('id' => '173','username' => 'Shortcode','release_name' => 'SIKASEM','songs' => 'Shortcode ft Amakye The Rapper-Sikasem(Prod by BrakayDiDiT).mp3','status' => 'Good','trans_time' => '13:15:31pm','trans_date' => '2020-12-11'),
            array('id' => '174','username' => 'mayteemusic@gmail.com','release_name' => 'ODO ADWOODWOO','songs' => 'MayTee - Odo adwoodwoo (Prod By De Beatz Murderer).mp3','status' => 'Good','trans_time' => '01:04:18am','trans_date' => '2020-12-16'),
            array('id' => '175','username' => 'Bryne0547','release_name' => 'SIKA DUROO','songs' => 'sika duro - fuck peace moni.mp3','status' => 'Good','trans_time' => '12:35:21pm','trans_date' => '2020-12-18'),
            array('id' => '176','username' => 'princekoomson3@gmail.com','release_name' => 'THE STICK EP','songs' => '','status' => 'Good','trans_time' => '14:03:22pm','trans_date' => '2020-12-18'),
            array('id' => '177','username' => 'princekoomson3@gmail.com','release_name' => 'THE STICK EP','songs' => 'Street4tune ft BpmBoss_Lock Up_(Prod by BpmBoss).mp3','status' => 'Good','trans_time' => '14:03:22pm','trans_date' => '2020-12-18'),
            array('id' => '178','username' => 'princekoomson3@gmail.com','release_name' => 'THE STICK EP','songs' => 'N3gava..mp3','status' => 'Good','trans_time' => '14:03:22pm','trans_date' => '2020-12-18'),
            array('id' => '179','username' => 'princekoomson3@gmail.com','release_name' => 'THE STICK EP','songs' => 'Street4TUNE-Ashanti Kotokor_(Mixed by BpmBoss).mp3.mp3','status' => 'Good','trans_time' => '14:03:22pm','trans_date' => '2020-12-18'),
            array('id' => '180','username' => 'Samkrew','release_name' => 'POVERTY','songs' => 'Samkrew - Poverty.mp3','status' => 'Good','trans_time' => '20:03:33pm','trans_date' => '2020-12-19'),
            array('id' => '181','username' => 'Minister Assan','release_name' => 'AHENE MU HENE','songs' => 'MinisterAssan - Ahene mu Hene.wav','status' => 'Good','trans_time' => '19:03:30pm','trans_date' => '2020-12-29'),
            array('id' => '182','username' => '7ilaw','release_name' => 'JUICE AND SAUCE','songs' => 'Tilaw juice and sauce .mp3','status' => 'Bad','trans_time' => '12:58:21pm','trans_date' => '2020-12-30'),
            array('id' => '183','username' => 'Arold','release_name' => 'MANWENSEM','songs' => 'Manwensem.mp3','status' => 'Good','trans_time' => '10:39:04am','trans_date' => '2021-01-01'),
            array('id' => '184','username' => 'Arold','release_name' => 'BOLGATANGA GIRL','songs' => 'Bolgatanga Girl.mp3','status' => 'Good','trans_time' => '10:41:47am','trans_date' => '2021-01-01'),
            array('id' => '185','username' => 'mrpercy','release_name' => 'LONELY','songs' => 'Lonely ft Flowking Stone.mp3','status' => 'Good','trans_time' => '10:49:46am','trans_date' => '2021-01-01'),
            array('id' => '186','username' => 'Dvozriona3iPSzSbWS6NDg==','release_name' => 'E9Y8JjpdFiGiSWg7Gkq7AA==','songs' => 'Piu4JeoCkrN9wZBd6AyDyQtfgXP7lHlhyi0JonaYR1uEOn7Z9+0sM3lH6zlEzFNLcDAT0hflmSp06Ya1IEEDlA==','status' => '3R06tDVbaEhAaqhHL5TGZg==','trans_time' => '10:44:53am','trans_date' => '2021-01-09'),
            array('id' => '187','username' => 'yawtog','release_name' => 'QZNJW2056562','songs' => 'Africa.mp3','status' => 'Good','trans_time' => '10:59:57am','trans_date' => '2021-01-09'),
            array('id' => '188','username' => 'yawtog','release_name' => 'QZMEM2039170','songs' => 'Daben.mp3','status' => 'Good','trans_time' => '11:02:28am','trans_date' => '2021-01-09'),
            array('id' => '189','username' => 'Ramiforson','release_name' => 'OHEMAA','songs' => 'Ohemaa (Prod. by Lweyz Beatz) | Hipradar.net','status' => 'Good','trans_time' => '03:41:21am','trans_date' => '2021-01-10'),
            array('id' => '190','username' => 'Anim','release_name' => 'BLACKNESS','songs' => '','status' => 'Good','trans_time' => '14:17:40pm','trans_date' => '2021-01-10'),
            array('id' => '191','username' => 'Roy deezy','release_name' => 'ENKWA NA EHIA','songs' => 'Enkwa Na Ehia','status' => 'Good','trans_time' => '00:25:31am','trans_date' => '2021-01-11'),
            array('id' => '192','username' => 'Abisah','release_name' => 'AFRICA PICTURE','songs' => 'Lyrix Abisah - Africa [Prod-by-Master C].mp3','status' => 'Good','trans_time' => '01:20:31am','trans_date' => '2021-01-19'),
            array('id' => '193','username' => 'Psyco','release_name' => 'NO ENTRY','songs' => 'No Entry_Mixed By aGhenzyBeat','status' => 'Good','trans_time' => '19:38:04pm','trans_date' => '2021-01-24'),
            array('id' => '194','username' => 'Lopezjnr','release_name' => 'TIME NO DE','songs' => 'DJ Lopez x Neon  -Time no dey - (mixed by Esany ).mp3','status' => 'Good','trans_time' => '10:05:03am','trans_date' => '2021-01-26'),
            array('id' => '195','username' => 'jessygh','release_name' => 'TIRED OF YA','songs' => 'Jessy - Malaaka(Prod by MOG Beatz).mp3','status' => 'Good','trans_time' => '07:59:05am','trans_date' => '2021-01-28'),
            array('id' => '196','username' => 'Kay Pee','release_name' => 'RIDE','songs' => 'Ride.mp3','status' => 'Good','trans_time' => '11:22:32am','trans_date' => '2021-01-30'),
            array('id' => '197','username' => 'I-Prinze','release_name' => 'MEDO WO FT DDT','songs' => 'Medo wo [Mixed by Survivor be','status' => 'Good','trans_time' => '16:09:23pm','trans_date' => '2021-01-31'),
            array('id' => '198','username' => 'SistaAfia','release_name' => '758869368426','songs' => 'Sika ft Kweku Flick.mp3','status' => 'Good','trans_time' => '13:47:49pm','trans_date' => '2021-02-04'),
            array('id' => '199','username' => 'Zigi Brown','release_name' => 'BET NNY3','songs' => 'selectZigi_Brown_-_bet_nnye.m4a.mp3','status' => 'Bad','trans_time' => '11:28:29am','trans_date' => '2021-02-05'),
            array('id' => '200','username' => 'Zigi Brown','release_name' => 'BET NNY3.','songs' => 'selectZigi_Brown_-_bet_nnye.m4a.mp3','status' => 'Good','trans_time' => '11:33:25am','trans_date' => '2021-02-05'),
            array('id' => '201','username' => 'OokomfoooKwadee33','release_name' => '755773131634','songs' => 'The Compilation.mp3','status' => 'Good','trans_time' => '14:51:24pm','trans_date' => '2021-02-05'),
            array('id' => '202','username' => 'YAW BERK','release_name' => '703557382161','songs' => 'This Is Music.mp3','status' => 'Good','trans_time' => '16:15:51pm','trans_date' => '2021-02-05'),
            array('id' => '203','username' => 'BlackEagleEntertainment','release_name' => '789554358194','songs' => 'Holy Night.mp3','status' => 'Good','trans_time' => '16:22:30pm','trans_date' => '2021-02-05'),
            array('id' => '204','username' => 'BlackEagleEntertainment','release_name' => '703557382499','songs' => 'High on Life.mp3','status' => 'Good','trans_time' => '16:26:34pm','trans_date' => '2021-02-05'),
            array('id' => '205','username' => 'BlackEagleEntertainment','release_name' => '703557357770','songs' => 'HENE.mp3','status' => 'Good','trans_time' => '16:34:58pm','trans_date' => '2021-02-05'),
            array('id' => '206','username' => 'BlackEagleEntertainment','release_name' => '789554193207','songs' => 'My Name is Black.mp3','status' => 'Good','trans_time' => '16:40:31pm','trans_date' => '2021-02-05'),
            array('id' => '207','username' => 'fredarhymz','release_name' => '789554396097','songs' => 'Who Be Dis.mp3','status' => 'Good','trans_time' => '16:47:13pm','trans_date' => '2021-02-05'),
            array('id' => '208','username' => 'fredarhymz','release_name' => 'PUBLIC OPINION','songs' => 'Public Opinion.mp3','status' => 'Good','trans_time' => '22:42:12pm','trans_date' => '2021-02-05'),
            array('id' => '209','username' => 'Zigi Brown','release_name' => '.BET NNY3.','songs' => 'selectZigi_Brown_-_bet_nnye.m4a.mp3','status' => 'Good','trans_time' => '10:10:40am','trans_date' => '2021-02-06'),
            array('id' => '210','username' => 'LilWinKwadwo','release_name' => '789554342254','songs' => 'Didi Matem.mp3','status' => 'Good','trans_time' => '22:54:36pm','trans_date' => '2021-02-11'),
            array('id' => '211','username' => 'Zigi Brown','release_name' => 'ANTES','songs' => 'ANTES.mp3','status' => 'Good','trans_time' => '10:24:42am','trans_date' => '2021-02-23'),
            array('id' => '212','username' => 'Zigi Brown','release_name' => 'HUSTLER','songs' => 'samyflex020.mp3','status' => 'Bad','trans_time' => '22:14:41pm','trans_date' => '2021-02-23'),
            array('id' => '213','username' => 'Peniel Velly','release_name' => 'DOWN THE STREET','songs' => 'PENIEL VELLY - DOWN THE STREET .mp3','status' => 'Good','trans_time' => '22:47:16pm','trans_date' => '2021-02-24'),
            array('id' => '214','username' => 'Hosfred1','release_name' => 'MON GAME','songs' => 'Hosfred-ft-Ketco-x-Yung Rich-x-Justice-MoneyGame-.mp3','status' => 'Good','trans_time' => '00:10:50am','trans_date' => '2021-03-02'),
            array('id' => '215','username' => 'Hosfred1','release_name' => 'EVERYDAY','songs' => 'Everyday - Kofi Jay x Y.N Gh {mixed by Lh}.mp3','status' => 'Good','trans_time' => '20:27:36pm','trans_date' => '2021-03-02'),
            array('id' => '216','username' => 'Yang Tuu Entertainment','release_name' => 'CHAMPANGNE','songs' => '- CHRISS E POP- CHAMPAGNE (Prod by C-Minor )','status' => 'Good','trans_time' => '15:23:46pm','trans_date' => '2021-03-07'),
            array('id' => '217','username' => 'Yang Tuu Entertainment','release_name' => 'POP- CHAMPAGNE','songs' => '- CHRISS E POP- CHAMPAGNE (Prod by C-Minor )','status' => 'Good','trans_time' => '23:04:55pm','trans_date' => '2021-03-08'),
            array('id' => '218','username' => 'Yang Tuu Entertainment','release_name' => 'POP CHAMPAGNE','songs' => 'CHRISS-E-POP-CHAMPAGNE-Prod-by-C','status' => 'Good','trans_time' => '23:53:53pm','trans_date' => '2021-03-08'),
            array('id' => '219','username' => 'Amerado','release_name' => '759159395702','songs' => 'Dawgi ft Sarkodie.mp3','status' => 'Good','trans_time' => '10:23:14am','trans_date' => '2021-03-09'),
            array('id' => '220','username' => 'Amerado','release_name' => '703557401633','songs' => 'Best Rapper.mp3','status' => 'Good','trans_time' => '10:27:29am','trans_date' => '2021-03-09'),
            array('id' => '221','username' => 'Arold','release_name' => '789554440721','songs' => 'Yeeko ft Kuami Eugene.mp3','status' => 'Good','trans_time' => '10:38:26am','trans_date' => '2021-03-09'),
            array('id' => '222','username' => 'opankagh','release_name' => '789554087711','songs' => 'Eka Aba Fie ft Shatta Wale.mp3','status' => 'Good','trans_time' => '14:39:30pm','trans_date' => '2021-03-09'),
            array('id' => '223','username' => 'Arold','release_name' => 'YOUTUBE','songs' => 'YOUTUBE.mp3','status' => 'Good','trans_time' => '15:22:06pm','trans_date' => '2021-03-09'),
            array('id' => '224','username' => 'Royal Productions','release_name' => 'NIGHT MEDITATION NOCTURNAL BEAT','songs' => 'Nocturnal Beats 11-01-2021 07-06.wav','status' => 'Good','trans_time' => '10:44:41am','trans_date' => '2021-03-13'),
            array('id' => '225','username' => 'Royal Productions','release_name' => 'NIGHT MEDITATION NOCTURNAL BEAT','songs' => 'Nocturnal Beats 11-01-2021 07-09.wav','status' => 'Good','trans_time' => '10:44:41am','trans_date' => '2021-03-13'),
            array('id' => '226','username' => 'Mr 2five','release_name' => 'SPECIAL ONE','songs' => '','status' => 'Good','trans_time' => '08:05:16am','trans_date' => '2021-03-19'),
            array('id' => '227','username' => 'BOY TEE YORR','release_name' => 'BOY TEE','songs' => 'IMG-20201126-WA0004.jpg','status' => 'Good','trans_time' => '11:27:49am','trans_date' => '2021-03-23'),
            array('id' => '228','username' => 'BOY TEE YORR','release_name' => 'BOY TEE YORR','songs' => 'AUD-20201212-WA0279.mp3','status' => 'Good','trans_time' => '11:38:22am','trans_date' => '2021-03-23'),
            array('id' => '229','username' => 'Kueku Benz','release_name' => 'HUSTLE GO PAY(PROD.BY DOPENATION)','songs' => 'Kueku Benz-Hustle Go Pay','status' => 'Good','trans_time' => '18:18:25pm','trans_date' => '2021-03-25'),
            array('id' => '230','username' => 'Nii Gh','release_name' => 'MAKOMA','songs' => 'Nii Gh MAK??MA (Mixed by Djae Banky).mp3','status' => 'Good','trans_time' => '11:35:50am','trans_date' => '2021-03-26'),
            array('id' => '231','username' => 'Nii Gh','release_name' => '3BOSO','songs' => 'Nii Gh ft Bigg Bone 3boso (Prod.by Djae Banky).mp3','status' => 'Good','trans_time' => '17:11:17pm','trans_date' => '2021-03-27'),
            array('id' => '232','username' => 'Street Bwoys','release_name' => 'MAMA','songs' => 'Twist parker- Mama [Prod. by Survivor beatz].mp3','status' => 'Good','trans_time' => '15:38:02pm','trans_date' => '2021-03-29'),
            array('id' => '233','username' => 'Saintgilbert1','release_name' => 'SUCCESS','songs' => 'Yung Famacy - Success_(mixed.by.yaw geng).mp3','status' => 'Good','trans_time' => '08:26:41am','trans_date' => '2021-04-15'),
            array('id' => '234','username' => 'Kleinmusic','release_name' => 'MONEY IN MIND','songs' => '','status' => 'Good','trans_time' => '02:14:50am','trans_date' => '2021-04-18'),
            array('id' => '235','username' => '21kelly','release_name' => 'TARGET','songs' => 'TARGET ? MM.mp3','status' => 'Good','trans_time' => '16:09:52pm','trans_date' => '2021-04-23'),
            array('id' => '236','username' => 'Untouchable Pablo','release_name' => 'MO NA MOBR3','songs' => 'Untouchable_Pablo_x_Young_Skass_-_Drip_-_mixed_by_B&D.mp3','status' => 'Good','trans_time' => '01:41:48am','trans_date' => '2021-05-08'),
            array('id' => '237','username' => '8LVnaG1RNK8qZ1fcuL9yEQ==','release_name' => 'U4Jcq2Wbgwk8+9bLMMdKhtQF2ewgoXuGHmJGC/kLCxC0F6pVtPLmG3uuJnJ2hOuq','songs' => 'GUydEnCCuXS+2iuDcREISPjWksG5r+vnHf1LuN9zzWVryDJQ/Rms2vBqgFxx7GV2AoXChDATTAQ5ZD1uC3gz2Q==','status' => '3R06tDVbaEhAaqhHL5TGZg==','trans_time' => '03:02:13am','trans_date' => '2021-05-08'),
            array('id' => '238','username' => 'SistaAfia','release_name' => 'PARTY','songs' => 'Party.mp3','status' => 'Good','trans_time' => '12:05:35pm','trans_date' => '2021-05-08'),
            array('id' => '239','username' => 'SistaAfia','release_name' => 'YOU GOT NERVES','songs' => 'U Got Nerves.mp3','status' => 'Good','trans_time' => '12:09:55pm','trans_date' => '2021-05-08'),
            array('id' => '240','username' => 'SistaAfia','release_name' => 'WMT','songs' => 'WMT.mp3','status' => 'Good','trans_time' => '12:14:15pm','trans_date' => '2021-05-08'),
            array('id' => '241','username' => 'SistaAfia','release_name' => 'PAPER','songs' => 'Paper ft Victor AD.mp3','status' => 'Good','trans_time' => '12:22:17pm','trans_date' => '2021-05-08'),
            array('id' => '242','username' => 'SistaAfia','release_name' => 'WEATHER','songs' => 'Weather.mp3','status' => 'Good','trans_time' => '12:31:58pm','trans_date' => '2021-05-08'),
            array('id' => '243','username' => 'SistaAfia','release_name' => 'CORNER CORNER','songs' => 'Corner Corner.mp3','status' => 'Good','trans_time' => '12:35:22pm','trans_date' => '2021-05-08'),
            array('id' => '244','username' => 'SistaAfia','release_name' => 'STREER','songs' => 'Street ft Akiyana.mp3','status' => 'Good','trans_time' => '12:40:32pm','trans_date' => '2021-05-08'),
            array('id' => '245','username' => 'SistaAfia','release_name' => 'QUEEN SOLOMON','songs' => 'Queen Solomon.mp3','status' => 'Good','trans_time' => '12:46:00pm','trans_date' => '2021-05-08'),
            array('id' => '246','username' => 'SistaAfia','release_name' => 'BROKEN','songs' => 'Broken.mp3','status' => 'Good','trans_time' => '12:53:03pm','trans_date' => '2021-05-08'),
            array('id' => '247','username' => 'Amerado','release_name' => 'TAXI DRIVER','songs' => 'Taxi Driver.mp3','status' => 'Good','trans_time' => '14:14:30pm','trans_date' => '2021-05-08'),
            array('id' => '248','username' => 'LilWinKwadwo','release_name' => 'CORNER CORNER','songs' => 'Corner Corner.mp3','status' => 'Good','trans_time' => '15:27:50pm','trans_date' => '2021-05-08'),
            array('id' => '249','username' => 'LilWinKwadwo','release_name' => 'LADDER','songs' => 'Ladder.mp3','status' => 'Good','trans_time' => '16:59:56pm','trans_date' => '2021-05-08'),
            array('id' => '250','username' => 'LilWinKwadwo','release_name' => 'KOTE KROM','songs' => 'Kote Krom.mp3','status' => 'Good','trans_time' => '17:03:43pm','trans_date' => '2021-05-08'),
            array('id' => '251','username' => 'mrpercy','release_name' => 'ARE YOU OKAY','songs' => 'Are You Okay.mp3','status' => 'Good','trans_time' => '19:08:02pm','trans_date' => '2021-05-08'),
            array('id' => '252','username' => 'YAW BERK','release_name' => 'A BETTER MAN','songs' => 'A Better Man.mp3','status' => 'Good','trans_time' => '19:50:50pm','trans_date' => '2021-05-08'),
            array('id' => '253','username' => 'KirkAfric','release_name' => 'MA.MA','songs' => '16205040916731796075400.jpg','status' => 'Good','trans_time' => '20:02:10pm','trans_date' => '2021-05-08'),
            array('id' => '254','username' => 'Phrimpong','release_name' => 'NKOMO','songs' => 'Nkomo.mp3','status' => 'Good','trans_time' => '22:08:36pm','trans_date' => '2021-05-08'),
            array('id' => '255','username' => 'Phrimpong','release_name' => 'WOA WO LY','songs' => 'Woa Wo Ly.mp3','status' => 'Good','trans_time' => '22:12:12pm','trans_date' => '2021-05-08'),
            array('id' => '256','username' => 'Phrimpong','release_name' => 'OHIA','songs' => 'Ohia.mp3','status' => 'Good','trans_time' => '22:14:31pm','trans_date' => '2021-05-08'),
            array('id' => '257','username' => 'Fantana','release_name' => 'NO DULLING','songs' => 'No Dulling.mp3','status' => 'Good','trans_time' => '22:51:08pm','trans_date' => '2021-05-08'),
            array('id' => '258','username' => 'KirkAfric','release_name' => '(MAMA)','songs' => 'Kirk - Mama - - Prod - By - Apya -wav.wav','status' => 'Good','trans_time' => '10:36:10am','trans_date' => '2021-05-09'),
            array('id' => '259','username' => 'Halfdolla','release_name' => 'SURUGU 1','songs' => 'surugu1.mp3','status' => 'Good','trans_time' => '01:32:22am','trans_date' => '2021-05-11'),
            array('id' => '260','username' => 'SistaAfia','release_name' => 'YOUTUBE REVENUE','songs' => 'YouTube.mp3','status' => 'Good','trans_time' => '12:11:58pm','trans_date' => '2021-05-11'),
            array('id' => '261','username' => 'LilWinKwadwo','release_name' => 'YOUTUBE REVENUE','songs' => 'YouTube.mp3','status' => 'Good','trans_time' => '12:16:20pm','trans_date' => '2021-05-11'),
            array('id' => '262','username' => 'Rhanskid','release_name' => 'NO WORRIES','songs' => 'NO WORIES..mp3','status' => 'Good','trans_time' => '22:55:06pm','trans_date' => '2021-05-11'),
            array('id' => '263','username' => 'tasante541@gmail.com','release_name' => 'GUCCI YUNG 1','songs' => 'AUDIO-2021-05-12-16-13-39.mp3','status' => 'Good','trans_time' => '16:28:06pm','trans_date' => '2021-05-12'),
            array('id' => '264','username' => 'GenewGuy_','release_name' => 'MONEY','songs' => 'Money(prod.by_Apya)','status' => 'Good','trans_time' => '23:02:52pm','trans_date' => '2021-05-12'),
            array('id' => '265','username' => 'GenewGuy_','release_name' => 'FREESTYLE','songs' => 'Genuine_Guy_Freestyle__Dior_Cover_','status' => 'Good','trans_time' => '23:46:13pm','trans_date' => '2021-05-12'),
            array('id' => '266','username' => 'tasante541@gmail.com','release_name' => 'SURUGU1','songs' => 'AUDIO-2021-05-12-16-13-39.mp3','status' => 'Good','trans_time' => '00:40:07am','trans_date' => '2021-05-14'),
            array('id' => '267','username' => 'MICKY','release_name' => 'EFHYA','songs' => 'Afya_Prod.By Nana Beatz','status' => 'Good','trans_time' => '14:41:01pm','trans_date' => '2021-05-16'),
            array('id' => '268','username' => 'Lyrikin','release_name' => 'SUCCESS.','songs' => 'Lyrikin - Success (Prod by BrakayDiDiT).mp3','status' => 'Good','trans_time' => '19:00:11pm','trans_date' => '2021-05-25'),
            array('id' => '269','username' => 'Lyrikin','release_name' => 'SUCCESS!','songs' => 'Lyrikin - Success (Prod by BrakayDiDiT).mp3','status' => 'Good','trans_time' => '20:18:45pm','trans_date' => '2021-05-25'),
            array('id' => '270','username' => 'Lyrikin','release_name' => 'SUCCESS...','songs' => 'Lyrikin - Success (Prod by BrakayDiDiT).mp3','status' => 'Good','trans_time' => '16:42:24pm','trans_date' => '2021-05-26'),
            array('id' => '271','username' => 'pee ronny','release_name' => 'ODO YE WU','songs' => 'PEE RONNY - ODO Y3 WU - PROD. BY M.M.B.mp3','status' => 'Good','trans_time' => '12:02:01pm','trans_date' => '2021-05-31'),
            array('id' => '272','username' => 'intldjx','release_name' => 'PAPPIN N LAUGHIN','songs' => '','status' => 'Good','trans_time' => '02:06:55am','trans_date' => '2021-06-05'),
            array('id' => '273','username' => 'Rhanskid','release_name' => 'MONEY AND LOVE','songs' => 'AUD-20201214-WA0017.mp3','status' => 'Good','trans_time' => '00:10:31am','trans_date' => '2021-06-07'),
            array('id' => '274','username' => 'Phrimpong','release_name' => 'THAT LINE','songs' => 'That Line.mp3','status' => 'Good','trans_time' => '08:39:45am','trans_date' => '2021-06-08'),
            array('id' => '275','username' => 'SistaAfia','release_name' => 'JEJE','songs' => 'Jeje.mp3','status' => 'Good','trans_time' => '08:44:36am','trans_date' => '2021-06-08'),
            array('id' => '276','username' => 'Amerado','release_name' => 'ME HO Y3','songs' => 'Me Ho Y3.mp3','status' => 'Good','trans_time' => '10:08:54am','trans_date' => '2021-06-08'),
            array('id' => '277','username' => 'LilWinKwadwo','release_name' => 'MAMA BOSS PAPA','songs' => 'Mama Boss Papa.mp3','status' => 'Good','trans_time' => '10:23:25am','trans_date' => '2021-06-08'),
            array('id' => '278','username' => 'LilWinKwadwo','release_name' => 'ANNOINTING','songs' => 'Annointing ft Kuami Eugene.mp3','status' => 'Good','trans_time' => '10:27:29am','trans_date' => '2021-06-08'),
            array('id' => '279','username' => 'LilWinKwadwo','release_name' => 'WOB3TI KPOO','songs' => 'Wob3ti Kpoo.mp3','status' => 'Good','trans_time' => '10:29:24am','trans_date' => '2021-06-08'),
            array('id' => '280','username' => 'LilWinKwadwo','release_name' => 'WAAHW3','songs' => 'WaaHw3.mp3','status' => 'Good','trans_time' => '10:31:39am','trans_date' => '2021-06-08'),
            array('id' => '281','username' => 'ZackGH','release_name' => 'ANSWER','songs' => 'Answer.mp3','status' => 'Good','trans_time' => '07:58:10am','trans_date' => '2021-06-12'),
            array('id' => '282','username' => 'ZackGH','release_name' => 'MEHIA SIKA','songs' => 'Mehia Sika.mp3','status' => 'Good','trans_time' => '08:00:38am','trans_date' => '2021-06-12'),
            array('id' => '283','username' => 'KirkAfric','release_name' => 'YENGYE YANI','songs' => 'med_ab_faq.pdf','status' => 'Good','trans_time' => '17:52:19pm','trans_date' => '2021-06-17'),
            array('id' => '284',
            'username' => 'Pop',
            'release_name' => 'EVANS AGYEMANG',
            'songs' => 'Evangelist Qwajo Agyemang- The Wrath Of God.mp3',
            'status' => 'Good',
            'trans_time' => '17:54:03pm',
            'trans_date' => '2021-06-19'),
            array('id' => '285','username' => 'Bantama','release_name' => 'FREE LIKE BIRD','songs' => 'Genius_Free_Prod. by Khendi','status' => 'Good','trans_time' => '08:59:09am','trans_date' => '2021-06-21')
          );
          


          $songs=json_decode(json_encode($songs));

          foreach ($songs as $item)

          {
              DB::table('songs')->insertOrignore(
                  
                [
                    'username' => $item->username,
                    'release' => $item->release_name,
                    'song' => $item->songs,
                    'status' => $item->status, 
                    
                ]       

              );
          }



    }
}
